<?php
    $helper = $this->helper("Lofmp\PriceComparison\Helper\Data");
    $_helper = $this->helper('Lof\MarketPlace\Helper\Data');
    $queryString = $helper->getQueryString();
    $collection = $this->getAllProducts();
    $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
?>
<div class="page-title">
      <div class="title_left">
        <h3><?php echo __('Add a Product');?></h3>
      </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
             <div class="x_title">
                <h4><?php echo __('The product you are adding may already exist on store. Search our catalog for the product you want to sell and save yourself some time.'); ?></h4>
                <div class="clearfix"></div>
             </div>
             <div class="x_content">
                 <form method="get" action="<?php echo $this->getUrl('lofmppricecomparison/product/view'); ?>" id="lofmppricecomparison_product_form" enctype="multipart/form-data" method="post" data-role="form-profile-validate" data-mage-init='{"validation":{}}'>
                     <div class="admin__fieldset-wrapper-content">
                        <fieldset class="admin__fieldset">
                            <div class="admin__field _required">
                                <label class="admin__field-label">
                                    <span><?php echo __("Search products in store"); ?></span>
                                </label>
                                <div class="admin__field-control">
                                    <input type="text" value="<?php echo $queryString; ?>" name="key_search" class="admin__control-text required-entry" placeholder="<?php echo __('Enter your product name or SKU');?>" />
                                </div>
                            </div>

                        </fieldset>
                        <div class="actions-toolbar">
                            <div class="primary">

                                <button type="submit" class="action continue primary" title="Continue"><span><?php echo __('Search');?></span></button>
                            </div>
                        </div>
                        <div class="assign-new-product">
                        <p></p>
                        <p><?php echo __('If it is not in store catalog:').'<a href="'.$this->getUrl('catalog/product/new/set/4/type/simple').'">'.__('Create a new product')?></a></p>
                        </div>
                    </div>
                 </form>
                 
             </div>
        </div>
    </div>

    <?php if ($collection->getSize()) { ?>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
             <div class="x_title">
                <h4><?php echo __('Result Product'); ?></h4>
                <div class="clearfix"></div>
             </div>

            <div class="x_content">
                <div class="table-responsive">
                    <table id="datatable" class="table table-striped table-bordered">
                        <thead>
                              <tr class="headings">
                                <th class="column-title"><?php echo __('Id');?> </th>
                                <th class="column-title"><?php echo __('Products');?> </th>
                                <th class="column-title"><?php echo __('Name');?> </th>
                                <th class="column-title"><?php echo __('Sku');?> </th>
                                <th class="column-title"><?php echo __('Price');?> </th>
                                <th class="column-title"><?php echo __('Action');?> </th>
                              </tr>
                        </thead>
                        <?php foreach ($collection as $product): ?>
                            <?php
                            
                            $image = 'category_page_list';
                            $productImage = $_helper->getMediaUrl().'catalog/product'.$product->getData('small_image');
                            $price = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($product->getFinalPrice(), true, false);
                            ?>
                        <tr>
                            <td class="col"><?php echo $product->getId(); ?></td>
                            <td class="col"><img width="100px" src="<?php echo $productImage; ?>" /></td>
                            <td class="col"><?php echo $product->getName(); ?></td>
                            <td class="col"><?php echo $product->getSku(); ?></td>
                            <td class="col"><?php echo $price; ?></td>
                            <td class="col lof-ap-btn-col">
                                <a href="<?php echo $this->getUrl('lofmppricecomparison/product/add')."id/".$product->getId(); ?>">
                                <button type="submit" class="action continue primary" title="Continue"><span><?php echo __('Sell Yours');?></span></button>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>    
    </div>
    <?php } ?>
</div>