<?php

/** @var \Magento\Customer\Block\Address\Book $block */

/** @var \Lof\Gdpr\Helper\Data $helper */
$helper = $this->helper(\Lof\Gdpr\Helper\Data::class);

$defaultBillingAddressId  = $block->getDefaultBilling();
$defaultShippingAddressId = $block->getDefaultShipping();

if ($helper->allowDeleteDefaultAddress()): ?>
    <script type="text/javascript">
        //<![CDATA[
        require(['jquery'], function ($) {
            "use strict";

            <?php if ($defaultBillingAddressId): ?>

                var deleteBillingEl   = '<a class="action delete lof-gdpr-delete" href="#" role="delete-address" data-address="<?= /** @noEscape */ $defaultBillingAddressId ?>"><span><?= /** @noEscape */ __('Delete Address') ?></span></a>';
                var boxBillingActions = $('.block-addresses-default .box-address-billing .box-actions');

                if (boxBillingActions.length) {
                    boxBillingActions.append(deleteBillingEl);
                }
            <?php endif; ?>

            <?php if ($defaultShippingAddressId): ?>

                var deleteShippingEl = '<a class="action delete lof-gdpr-delete" href="#" role="delete-address" data-address="<?= /** @noEscape */ $defaultShippingAddressId ?>"><span><?= /** @noEscape */ __('Delete Address') ?></span></a>';
                var boxShippingActions = $('.block-addresses-default .box-address-shipping .box-actions');

                if (boxShippingActions.length) {
                    boxShippingActions.append(deleteShippingEl);
                }
            <?php endif; ?>
        });
        //]]>
    </script>
    <script type="text/x-magento-init">
    {
        ".block-addresses-default": {
            "address": {
                "deleteAddress": "a.lof-gdpr-delete[role='delete-address']",
                "deleteUrlPrefix": "<?= /** @noEscape */ $block->getUrl('customer/address/delete/') ?>id/"
            }
        }
    }
    </script>
<?php endif; ?>
