<?php
	$helper = $this->helper("Lof\MarketPlace\Helper\Data");
	$coupon_helper = $this->helper("Lofmp\CouponCode\Helper\Data");
	$data = $block->getCouponCode();
	$rule_data = $coupon_helper->getListActiveRules($helper->getSellerId());
?>
<div class="page-title">
  <div class="title_left">
    <h3><?php echo __('Coupon Code'); ?></h3>
  </div>
</div>
<div class="row">
  	<div class="col-md-12 col-sm-12 col-xs-12">
    	<div class="x_panel">
	      	<div class="x_title">
	        	<h2><?php echo __('All Coupon Code'); ?></h2>
	        	<div class="clearfix"></div>
	     	</div>
	      	<div class="x_content">
	      		<form data-mage-init='{"validation": {}}' class="entry-edit form-inline" action="<?php echo $block->getUrl('*/*/generate');?>" enctype="multipart/form-data" method="post" autocomplete="off">
	      			<div class="row" style="margin-bottom: 10px">
		      			<div class="col-md-2"></div>
		      			<div class="col-md-3">
		      				<div class="admin__field-control">
								<input type="text" name="email" class="admin__control-text required validate-email" placeholder="<?php echo __('Enter the customer email');?>" />
							</div>
		      			</div>
		      			<div class="col-md-2 text-center">
		      				<div class="admin__field-control">
								<select class="admin__control-select" style="padding-top: 0.6rem; padding-bottom: 0.6rem" name="rule_id">
								<?php foreach($rule_data as $key => $val){?>
									<option value="<?php echo $key; ?>"><?php echo $val; ?></option>
								<?php } ?>
								</select>
							</div>
		      			</div>
	      				<div class="primary" title="Save">
							<button class="action-default primary" title="Save " type="submit">
								<span><span>Generate Coupon</span></span>
							</button>
						</div>
		      		</div>
	      			<input type="hidden" name="seller_id" value="<?php echo $helper->getSellerId(); ?>">
	      		</form>
	      		<form action="<?php echo $block->getUrl('*/*/massdelete');?>" method="post" id="form_delete">
	      			<div class="row" style="margin-bottom: 10px">
	      				<div class="col-md-2">
	      					<a id="mass_delete" class="action-default primary" href="javascript:void(0)"><?php echo __("Mass Delete")?></a>
	      				</div>
	      			</div>

			        <table id="datatable" class="table table-striped table-bordered">
			          	<thead>
				          	<tr class="headings">
				          		<th class=""> <input type="checkbox" name="select-all" id="select-all" /> </th>
				                <th class="column-title"><?php echo __('Id');?> </th>
				                <th class="column-title"><?php echo __('Coupon Code');?> </th>
				                <th class="column-title"><?php echo __('Email');?> </th>
				                <th class="column-title"><?php echo __('Created At'); ?> </th>
				                <th class="column-title"><?php echo __('Expires At'); ?> </th>
				                <th class="column-title"><?php echo __('Rule Name'); ?> </th>
				                <th class="column-title"><?php echo __('Discount Amount'); ?> </th>
				                <th class="column-title no-link last"><span class="nobr"><?php echo __('Action'); ?></span>
				                </th>
				                <th class="bulk-actions" colspan="7">
				                  <a class="antoo" style="color:#fff; font-weight:500;"><?php echo __('Bulk Actions');?> ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
				                </th>
				          	</tr>
				        </thead>
				        <tbody>
				        	<?php
				        		foreach ($data as $key => $val) {
				        			$ruleinf = $coupon_helper->getRuleData($val["rule_id"])->getData();
				        	?>
					        <tr>
					        	<td class=""> <input type="checkbox" name="selected[]" value="<?php echo $val["couponcode_id"]; ?>" /> </td>
					         	<td class=""><?php echo $val["couponcode_id"]; ?></td>
					         	<td class=""><?php echo $val["code"]; ?></td>
					         	<td class=""><?php echo $val["email"]; ?></td>
					         	<td class=""><?php echo ($val["created_at"])? $block->formatDate($val["created_at"], \IntlDateFormatter::LONG) : '';?></td>
					         	<td class=""><?php echo ($val["expiration_date"])? $block->formatDate($val["expiration_date"], \IntlDateFormatter::LONG) : '';?></td>
					         	<td class=""><?php echo $ruleinf["name"];?></td>
					         	<td class=""><?php echo $coupon_helper->discountAmountFormat($ruleinf["rule_id"], $ruleinf["discount_amount"]);?></td>
					         	<td class="last text-center">
					         		<a class="delete_coupon" href="<?php echo $block->getUrl('*/*/delete?couponcode_id='. $val["couponcode_id"]);?>" style="font-size: larger; color: #EB5202"><i class="fa fa-trash" aria-hidden="true"></i></a>
					         	</td>
					        </tr>
					        <?php } ?>
				        </tbody>
			        </table>
			    </form>
	      	</div>
	    </div>
    </div>
 </div>
 <script type="text/javascript">
 	require(['jquery'], function($){
		$('#select-all').click(function(event) {
		    if(this.checked) {
		        $(':checkbox').each(function() {
		            this.checked = true;
		        });
		    }else{
		    	$(':checkbox').each(function() {
		            this.checked = false;
		        });
		    }
		});

		$(".delete_coupon").click(function(event){
			var url = $(this).attr('href');
			if(confirm('Are you sure you want to delete?')) {
		        window.location = url;
		    }else{
		    	return false;
		    }
		});
		$("#mass_delete").click(function(event){
			var exists = $('input[type=checkbox][name^=selected]:checked').length;
		    if( !exists ) {
		         alert('Please select at least 1 checkbox!');
		    } else if(confirm('Are you sure you want to delete?')) {
		         $('#form_delete').submit();
		    }
		});
 	});
 </script>


