<?php
namespace Lofmp\GdprSeller\Block\Seller;

use Lof\Gdpr\Helper\Data;
use Lof\MarketPlace\Model\Seller;
use Magento\Framework\App\ResourceConnection;
use Magento\Framework\Registry;
use Magento\Framework\View\Element\Template\Context;

/**
 * Class DeleteProfile
 * @package Lofmp\GdprSeller\Block\Seller
 */
class DeleteProfile extends \Magento\Framework\View\Element\Template {

	/**
     * Core registry
     *
     * @var Registry
     */
	protected $_coreRegistry = null;
    /**
     * @var Seller
     */
    protected $_sellerFactory;
    /**
     * @var Data
     */
    protected $_helper;
    /**
     * @var \ResourceConnection
     */
    protected $_resource;

    /**
     * @param Context $context
     * @param Registry $registry
     * @param Seller $sellerFactory
     * @param Data $helper
     * @param ResourceConnection
     */
	public function __construct(
        Context $context, Registry $registry, Seller $sellerFactory, Data $helper, ResourceConnection $resource
        ) {
		$this->_helper        = $helper;
		$this->_coreRegistry  = $registry;
		$this->_sellerFactory = $sellerFactory;
		$this->_resource      = $resource;
        parent::__construct($context);
    }
    /**
     *  get Seller Colection
     *
     * @return Object
     */
     public function getSellerCollection(){
        $sellerCollection = $this->_sellerFactory->getCollection();
        return $sellerCollection;
    }

    /**
     * @return string
     */
    public function getDeleteProfileUrl() {
         return $this->getUrl('catalog/seller/deleteprofile');
    }

    /**
     * @return string
     */
    public function getDeleteSellerUrl() {
        return $this->getUrl('catalog/seller/deleteseller');
    }

    /**
     * @return array|mixed
     */
    public function canDeleteSeller() {
        return $this->_helper->getConfigGeneral('allow_delete_seller');
    }

    /**
     * @return string
     */
    public function toHtml()
    {
        if($this->canDeleteSeller()) {
            return parent::toHtml(); // TODO: Change the autogenerated stub
        }
    }

}
