<?php
$sellerOrder = $this->getTheSellerOrder();
$orderObject = $block->getOrder();
$order = $orderObject;
$items = $block->getOrder()->getAllItems();
$invoice = $block->getInvoice();
$helper = $this->helper('Lof\MarketPlace\Helper\Data');
$objectManager   = \Magento\Framework\App\ObjectManager::getInstance ();
$orderitems = $objectManager->get('Lof\MarketPlace\Model\Orderitems');
$calculate        = $objectManager->get ( 'Lof\MarketPlace\Model\CalculateCommission' );
$orderEditLink = $block->getUrl("catalog/sales/orderview", ["id" => $orderObject->getId()]);

$sellerShipping = [];
if ($order->getMpInfo()) {
    $multiShippingInfo = json_decode($order->getMpInfo(), true);
    $sellerShipping = isset($multiShippingInfo[$block->getSellerId()]) ? $multiShippingInfo[$block->getSellerId()] : [];
}

if ($sellerShipping && isset($sellerShipping['price'])) {
    $shippingHandling = $sellerShipping['price'];
} else {
    $shippingHandling = $orderObject->getData('shipping_amount');
}
$orderCurrencyCode = $order->getOrderCurrencyCode();
$currentSellerId = $helper->getSellerId();
?>
<style type="text/css">
  #invoice_content {background-color: white;}
</style>
<div class="row lof_marketplace" id="test_id">
	<div class="col-md-12">
		<div class="x_panel">
			<div class="x_title">
            <h2><?= __('Invoice Design');?></h2>
            <div class="page-actions-buttons">
                <div class="actions-split save primary" title="Order">
                    <a href="javascript:" data-url="<?= $block->getUrl("sellerinvoice/invoice/downloadfile", ["id" => $invoice->getId()]); ?>" class="btn btn-primary lof_invoice" id="btnExport"><?= __('Export Pdf file'); ?></a>
                    <!-- <button type="button" class="btn btn-primary lof_invoice" id="cmd"><?= __('Export Pdf file'); ?></button> -->
                </div>
            </div>
          <div class="clearfix"></div>
      </div>
    	<div class="x_content" id="invoice_content">
    		<div class="content invoice">
    			<div class="row">
    				<div class="col-xs-12 invoice-header">
              <h1>
                <i class="fa fa-globe"></i> <?= __('Invoice'); ?>
                <small class="pull-right"><?= __('Create At');?>: <?= $invoice->getData('created_at');?></small>
              </h1>
            </div>
    			</div>
    			<div class="row invoice-info">
            <div class="col-sm-3 invoice-col">
              <b><?= __('Billing Address'); ?></b>
              <br>
            	<address>
                  <?= $this->getFormattedAddress(); ?>
              </address>
            </div>
            <!-- /.col -->
            <div class="col-sm-3 invoice-col">
              	<b><?= __('Shipping Address'); ?></b>
                <br>
              	<address>
              	<?= $this->getBillingAddress(); ?>
                </address>
            </div>
            <!-- /.col -->
            <div class="col-sm-3 invoice-col">
              <?php /* @escapeNotVerified */ echo __('<b>Invoice</b> # %1', $invoice->getIncrementId()) ?>
              <br>

               <?php /* @escapeNotVerified */ echo __('<b>Order:</b> # <a href="%1">%2</a>', $orderEditLink, $orderObject->getRealOrderId()) ?>
              <br>
              <b><?= __('Order Date');?>:</b> <?= $this->getOrderDate(); ?>
              <br>
              <b><?= __('Order Status'); ?>:</b> <?= $orderObject->getStatusLabel(); ?>
              <br>
              <b><?= __('Purchased From'); ?>:</b> <?= $this->getOrderStoreName(); ?>
            </div>
             <!-- /.col -->
            <div class="col-sm-3 invoice-col">
              	<b><?= __('Account Information '); ?></b>
              	<br>

              	<b><?= __('Customer Name');?>:</b> <?= $orderObject->getCustomerName(); ?>
              <br>
              <b><?= __('Email'); ?>:</b> <?= $orderObject->getCustomerEmail(); ?>
              <br>
              <b><?= __('Customer Group'); ?>:</b> <?= $this->getCustomerGroupName(); ?>
            </div>
          </div>
          <div class="row">
              <div class="col-xs-12 table">
                <table class="table table-striped  edit-order-table">
                  <thead>
                    <tr>
                    	<th><?= __('Product'); ?></th>
                    	<th><?= __('Price'); ?></th>
                      <th><?= __('Qty'); ?></th>
                      <th><?= __('Subtotal');?></th>
                      <th><?= __('Tax Amount');?></th>
                      <th><?= __('Discount Amount');?></th>
                       <th><?= __('Row Total');?></th>
                      <th><?= __('Admin Commission');?></th>
                      <th><?= __('Seller Total');?></th>
                      <th><?= __('Seller');?></th>
                    </tr>
                  </thead>
                  <tbody>
                  	<?php
                  	$subtotal = $tax = $discount = $grand_total = $seller_amount =$seller_total = 0;
                    $grand_total = $shippingHandling;
                  	foreach($items as $item) {
                      if ($item->getData('base_row_total') > 0)  {
                        $product_id = $item->getData('product_id');
                        $seller_id = $orderitems->load($item->getId(),'order_item_id')->getSellerId();

                        if ($seller_id == $currentSellerId) {
                          $product_id = $item->getData('product_id');
                          $subtotalIncl = $item->getData('base_row_total_incl_tax');
                          $discount_amount = $item->getData('discount_amount');
                          $tax_amount = $item->getData('tax_amount');
                          $total =   $item->getData('base_row_total');

                          $row_total =  $total + $tax_amount - $discount_amount;
                          $subtotal = $subtotal + $total;
                          $tax = $tax + $tax_amount;
                          $discount = $discount + $discount_amount;
                          $subtotalExcl = $row_total - $tax_amount;
                          $grand_total = $grand_total + $row_total;
                          $seller_name = $this->getSeller($product_id)->getData('name');
                          $seller_id = $this->getSeller($product_id)->getData('seller_id');
                          $admin_commission = $this->getOrderItems($product_id)->getData('admin_commission');
                          $seller_commission = $this->getOrderItems($product_id)->getData('seller_commission');

                          $seller_total += $seller_commission;

                          ?>
                        <tr>
                          <td>
                            <div class="product-title"><?= $item->getData('name');?></div>
                            <div class="product-sku-block"><span><?= __('SKU');?>:</span><?= $item->getData('sku');?></div>
                            <?php
                            if(isset($item->getData('product_options')['attributes_info'])) {
                              echo '<dl class="item-options">';
                                foreach ($item->getData('product_options')['attributes_info'] as $key => $attributes_info) {
                                  echo '<dt>'.$attributes_info['label'].'</dt>';
                                  echo '<dd>'.$attributes_info['value'].'</dd>';
                                }
                              echo '</dl>';
                            }
                            if(isset($item->getData('product_options')['options'])) {
                              echo '<dl class="item-options">';
                                foreach ($item->getData('product_options')['options'] as $key => $options) {
                                  echo '<dt>'.$options['label'].'</dt>';
                                  echo '<dd>'.$options['value'].'</dd>';
                                }
                              echo '</dl>';
                            }
                            ?>
                          </td>
                          <td><?= $helper->getPriceFomat($item->getData('price'), $orderCurrencyCode, 2);?></td>
                          <td><?= $item->getData('qty_invoiced');?></td>
                          <td><?= $helper->getPriceFomat($total, $orderCurrencyCode, 2);?></td>
                          <td><?= $helper->getPriceFomat($tax_amount, $orderCurrencyCode, 2);?></td>
                          <td><?= $helper->getPriceFomat($discount_amount, $orderCurrencyCode, 2);?></td>
                          <td><?= $helper->getPriceFomat($row_total, $orderCurrencyCode, 2);?></td>
                          <td><?= $helper->getPriceFomat($admin_commission, $orderCurrencyCode, 2); ?></td>
                          <td><?= $helper->getPriceFomat($seller_commission, $orderCurrencyCode, 2); ?></td>
                          <td><?= $seller_name; ?></td>
                        </tr>
   					      <?php }
                      }
                    } ?>
                  </tbody>
                </table>
            </div>
            <!-- /.col -->
          </div>
          <div class="row">
              <!-- accepted payments column -->
              <div class="col-xs-6">
                <p class="lead"><?= __('Payment Methods');?>:</p>
                <img src="<?= $block->getViewFileUrl('Lof_MarketPlace::images/visa.png') ?>" alt="Visa">
                <img src="<?= $block->getViewFileUrl('Lof_MarketPlace::images/mastercard.png') ?>"
                        alt="Mastercard">
                <img src="<?= $block->getViewFileUrl('Lof_MarketPlace::images/american_express.png') ?>"
                        alt="American Express">
                <img src="<?= $block->getViewFileUrl('Lof_MarketPlace::images/paypal.png') ?>" alt="Paypal">
                <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                  <?= $this->getOrder()->getPayment()->getMethodInstance()->getTitle(); ?>
                </p>
                <p><?= __('The order was placed using');?> <?= $this->getOrder()->getData('order_currency_code');?>.</p>
              </div>
              <!-- /.col -->
              <div class="col-xs-6">
                <p class="lead"><?= __('Invoice Totals');?></p>
                <div class="table-responsive">
                  <table class="table">
                    <tbody>
                      <tr>
                        <th style="width:50%"><?= __('Subtotal');?></th>
                        <td><?= $helper->getPriceFomat($subtotal, $orderCurrencyCode, 2); ?></td>
                      </tr>
                      <tr>
                        <th><?= __('Shipping & Handling');?></th>
                        <td><?= $helper->getPriceFomat($this->getOrder()->getData('shipping_amount'), $orderCurrencyCode, 2); ?></td>
                      </tr>
                      <tr>
                        <th><?= __('Tax');?></th>
                        <td><?= $helper->getPriceFomat($tax, $orderCurrencyCode, 2); ?></td>
                      </tr>
                       <tr>
                        <th><?= __('Discount');?></th>
                        <td><?= $helper->getPriceFomat(-$discount, $orderCurrencyCode, 2); ?></td>
                      </tr>
                       <tr>
                        <th><?= __('Grand Total');?></th>
                        <td><?= $helper->getPriceFomat($grand_total, $orderCurrencyCode, 2); ?></td>
                      </tr>
                       <tr>
                        <th><?= __('Seller Amount');?></th>
                        <td><?= $helper->getPriceFomat($seller_total, $orderCurrencyCode, 2); ?></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
              <!-- /.col -->
          </div>
          <!-- this row will not appear when printing -->
          <div class="row no-print">
              <div class="col-xs-12">
                <?= $block->getChildHtml('invoice.print.button'); ?>
                <button class="btn btn-default print-button" onclick="window.print();"><i class="fa fa-print"></i> <?= __("Print");?></button>
              </div>
          </div>
    		</div>
      </div>
		</div>
	</div>
</div>
<div id="editor"></div>
<script>
    require([
    'jquery',
    //'jspdf',
    //'html2canvas'
    ], function(jQuery, jsPdf) {
        jQuery(document).ready(function() {
            jQuery("#btnExport").click(function() {
                var url = jQuery(this).data("url");
                window.location = url;
                return false;
            })
            // jQuery('#cmd').click(function () {
            //     var d = new Date();
            //     var n = d.getTime();
            //     var doc = new jsPdf('l', 'pt', 'a4');
            //     doc.setFontSize(10);
            //     doc.addHTML(jQuery("#invoice_content")[0], 10, 10, {pagesplit: false, margin: {top: 10, right: 10, bottom: 10, left: 20, useFor: 'page'}}, function() {
            //         doc.save('invoice_'+ n +'.pdf');
            //     });
            // });
        });
    });
</script>
