<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Shipping\Block\Tracking\Link */ ?>
<?php $order = $block->getOrder() ?>
<a href="#" class="ves-popupwindow action track" data-name="trackorder" data-url="<?php /* @escapeNotVerified */ echo $block->getWindowUrl($order) ?>" title="<?php /* @escapeNotVerified */ echo $block->getLabel() ?>">
	<span><?php /* @escapeNotVerified */ echo $block->getLabel()?></span>
</a>
