<?php

namespace Lofmp\LayeredNavigation\Model\Layer\SellerHomePage;

class AvailabilityFlag extends \Magento\Catalog\Model\Layer\Category\AvailabilityFlag
{
    public function isEnabled($layer, array $filters = [])
    {

        return parent::isEnabled($layer, $filters); // TODO: Change the autogenerated stub
    }
}