
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$name = '';
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$url = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
if ($params = $block->getRequest()->getParams()) {
    $type= $params['type'];
    $endate =str_replace('.', '-', $params['to']);
    $startdate =str_replace('.', '-', $params['from']);
} else {
    $type= 'month';
    $startdate = date("Y-m-d", strtotime("-1 month"));
    $endate = date("Y-m-d");
}
$resourceCollection =  $objectManager->create('Lofmp\Rma\Model\ResourceModel\Item\Collection')->addFieldToFilter(
    'main_table.reason_id',
    ['notnull' => true]
)
        ->setPeriodType($type)
        ->setDateColumnFilter('created_at')
        ->addDateFromFilter($startdate)
        ->addDateToFilter($endate)
        ->_getSelectedColumns();
$collection = $resourceCollection->getData();
?>
<div class="filter">
<label><?= __("From");?></label>
<input name="datefrom" id="datefrom" value="<?php echo $startdate ?>" type="text">
<label><?= ("To");?></label>
<input name="dateto" id="dateto" value="<?php echo $endate ?>" type="text">
<label><?= ("Period");?></label>
<select name="selector" >
  <option value="year" <?php if ($type == 'year') { echo ' selected="selected"'; }?>><?= __("year");?></option>
  <option value="quarter"<?php if ($type == 'quarter') { echo ' selected="selected"'; }?> ><?= __("quarter");?></option>
  <option value="month" <?php if ($type == 'month') { echo ' selected="selected"'; } ?> ><?= __("month");?></option>
  <option value="day" <?php if ($type == 'day') { echo ' selected="selected"'; }?> ><?= __("day");?></option>
</select>
<button type="button" id='filter' ><?= __("Filter");?></button>
</div>
<script type="text/javascript">
require([
    "jquery",
    "mage/calendar"
    ], function($){
      $('#datefrom').datepicker({
            prevText: '&#x3c;zurück', prevStatus: '',
            prevJumpText: '&#x3c;&#x3c;', prevJumpStatus: '',
            nextText: 'Vor&#x3e;', nextStatus: '',
            nextJumpText: '&#x3e;&#x3e;', nextJumpStatus: '',
            monthNames: ['January','February','March','April','May','June',
            'July','August','September','October','November','December'],
            monthNamesShort: ['Jan','Feb','Mar','Apr','May','Jun',
            'Jul','Aug','Sep','Oct','Nov','Dec'],
            dayNames: ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
            dayNamesShort: ['Su','Mo','Tu','We','Th','Fr','Sa'],
            dayNamesMin: ['Su','Mo','Tu','We','Th','Fr','Sa'],
          showMonthAfterYear: false,
          dateFormat:'yy.mm.dd '
        } 
      );
        $('#dateto').datepicker({
          prevText: '&#x3c;zurück', prevStatus: '',
            prevJumpText: '&#x3c;&#x3c;', prevJumpStatus: '',
            nextText: 'Vor&#x3e;', nextStatus: '',
            nextJumpText: '&#x3e;&#x3e;', nextJumpStatus: '',
            monthNames: ['January','February','March','April','May','June',
            'July','August','September','October','November','December'],
            monthNamesShort: ['Jan','Feb','Mar','Apr','May','Jun',
            'Jul','Aug','Sep','Oct','Nov','Dec'],
            dayNames: ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
            dayNamesShort: ['Su','Mo','Tu','We','Th','Fr','Sa'],
            dayNamesMin: ['Su','Mo','Tu','We','Th','Fr','Sa'],
          showMonthAfterYear: false,
          dateFormat:'yy.mm.dd'
          });
          var t = $('#dateto').val();
          var  fr = $('#datefrom').val();
          var type = $('select[name=selector]').val();
          $( "#dateto" ).change(function() {
            t = $('#dateto').val();
        });
          $( "#datefrom" ).change(function() {
            fr = $('#datefrom').val();
        });
          $('select[name=selector]').change(function() {
            type = $('select[name=selector]').val();
        });
        $( "#filter" ).click(function() {
          window.location.href = '<?php echo $url ?>marketplace/catalog/rmareport/product?from='+fr+'&to='+t+'&type='+type;
       });
    });
</script>
<?php
if (count($collection)>0):
    ?>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawVisualization);
        var d = [];
        d.push(['datetime ','<?= __("Total RMA");?>','<?= __("Total Request");?>','<?= __("Total Return");?>']);
          <?php
            foreach ($collection as $value) {
                if (!$value['total_returned_cnt']) {
                    $value['total_returned_cnt'] = 0;
                }
                ?>
             d.push(['<?php echo $value['time'].'_'.$value['product_name'] ?>' ,<?php
                echo $value['total_rma_cnt'] ?>,<?php echo $value['total_requested_cnt'] ?>,<?php echo $value['total_returned_cnt'] ?>]);
             

                <?php
            }
            ?>
           

        function drawVisualization() {
        // Some raw data (not necessarily accurate)
        var data = google.visualization.arrayToDataTable(d);

    var options = {
      title : '<?= __("RMA Report By Product");?>',
      vAxis: {title: '<?= __("Number");?>'},
      hAxis: {title: '<?= __("Time_Product");?>'},
      seriesType: 'bars',
     /* series: {5: {type: 'line'}}*/
    };
    var chart = new google.visualization.ComboChart(document.getElementById('chart_div'));
    chart.draw(data, options);
}
</script>
<a id="export_link" target="_blank" style="float:right; z-index: 10000;position:relative;"><?= __("Save chart as an image");?></a>
<div id="chart_div" style="widht: 100%; height: 400px;"></div>
    <?php
endif;
?>