<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info */ ?>
<?php $_order = $block->getOrder() ?>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $helper = $objectManager->create('Lofmp\TimeDiscount\Helper\Data');
    $time_quote = $objectManager->create('Lofmp\TimeDiscount\Model\Quote');
?>
<div id="order-messages">
    <?php echo $block->getChildHtml('order_messages') ?>
</div>

<?php echo $block->getChildHtml('order_info') ?>
<input type="hidden" name="order_id" value="<?php /* @escapeNotVerified */ echo $_order->getId() ?>"/>

<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Payment &amp; Shipping Method') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method<?php if ($_order->getIsVirtual()): ?> order-payment-method-virtual<?php endif; ?>">
            <?php /* Payment Method */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Payment Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="order-payment-method-title"><?php echo $block->getPaymentHtml() ?></div>
                <div class="order-payment-currency"><?php /* @escapeNotVerified */ echo __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?></div>
                <div class="order-payment-additional">
                    <?php echo $block->getChildHtml('order_payment_additional'); ?>
                    <?php echo $block->getChildHtml('payment_additional_info'); ?>
                </div>
            </div>
        </div>
        <?php echo $block->getChildHtml('order_shipping_view') ?>
    </div>
</section>

<!-- start add delivery date -->
<?php if($helper->getConfig('general_settings/enable')):?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php echo __('Time Discount Information') ?></span>
    </div>
    <div class="admin__page-section-item order-delivery-date">
            <div class="admin__page-section-item-content">
                <div id="shipping-arrival-date">
                    <div>
                        <strong><?php echo __('Shipping Arrival Date: ') ?></strong>
                        <?php if($_order->getShippingArrivalDate()):?>
                            <span><?php echo $helper->formatDate($_order->getShippingArrivalDate());?></span>
                        <?php else:?>
                            <span><?php echo __('N/A');?></span>
                        <?php endif;?>
                    </div>
                    <div>
                        <strong><?php echo __('Shipping Arrival Timeslot: ') ?></strong>
                        <?php if($_order->getShippingArrivalTimeslot()):?>
                            <span><?php echo $_order->getShippingArrivalTimeslot();?></span>
                        <?php else:?>
                            <span><?php echo __('N/A');?></span>
                        <?php endif;?>
                    </div>
                    <?php if($helper->isShowShippingComment()) : ?>
                        <div>
                            <strong><?php echo __('Shipping Arrival Comments: ') ?></strong>
                            <?php if($_order->getShippingArrivalComments()):?>
                                <span><?php echo $_order->getShippingArrivalComments();?></span>
                            <?php else:?>
                                <span><?php echo __('No Comment');?></span>
                            <?php endif;?>
                        </div>
                    <?php endif;?>
                </div>
            </div>
        </div>
</section>
<?php endif;?>
<!-- end add delivery date -->
<?php echo $block->getGiftOptionsHtml() ?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Items Ordered') ?></span>
    </div>
    <?php echo $block->getItemsHtml() ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Order Total') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Notes for this Order') ?></span>
            </div>
            <?php echo $block->getChildHtml('order_history') ?>
        </div>

        <div class="admin__page-section-item order-totals">
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Order Totals') ?></span>
            </div>
            <?php echo $block->getChildHtml('order_totals') ?>
        </div>
    </div>
</section>

<?php echo $block->getChildHtml('popup_window');?>
