<?php
/**
 * @var Lofmp\Rma\Block\Marketplace\Grid $block
 */
$sellerRmaList = $block->getSellerRma();
?>
<div class="lof-mp-page-title page-title">
    <h2><?= $block->escapeHtml(__('Manage RMAs')) ?></h2>
</div>
<div class="x_content">
    <table id="datatable" class="table table-striped table-bordered">
        <thead>
        <tr class="headings">
            <th class="hidden"></th>
            <th class="column-title"><?= $block->escapeHtml(__('ID')) ?> </th>
            <th class="column-title"><?= $block->escapeHtml(__('Customer')) ?> </th>
            <th class="column-title"><?= $block->escapeHtml(__('Status')) ?> </th>
            <th class="column-title"><?= $block->escapeHtml(__('Created at')) ?> </th>
            <th class="column-title"><?= $block->escapeHtml(__('Order ID')) ?> </th>
            <th class="column-title"><?= $block->escapeHtml(__('Action')) ?> </th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($sellerRmaList as $rma):
            $viewUrl = $block->getUrl('catalog/rma/view', [
                'id' => $rma['rma_id']
            ]);
            ?>
            <tr class="even pointer">
                <td class="hidden"></td>
                <td><?= $block->escapeHtml($rma['rma_id']) ?></td>
                <td><?= $block->escapeHtml($rma['customer_firstname'] . ' ' . $rma['customer_lastname']) ?></td>
                <td><?= $block->escapeHtml($block->getStatusName($rma['status_id'])) ?></td>
                <td><?= $block->escapeHtml($rma['created_at']) ?></td>
                <td>#<?= $block->escapeHtml($rma['order_increment_id']) ?></td>
                <td class="last">
                    <a href="<?= $block->escapeUrl($viewUrl) ?>">
                        <?= $block->escapeHtml(__('View')) ?>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
