<?php
    $question = $block->_currentQuestion;
    $categoryId = $question->getCategoryId();
    $animation = $question->getAnimationClass();
    $productIds = $question->getRelateProductIds();

    $categoryCollection = $this->_categoryFactory;
    $categoryList = $categoryCollection->toOptionArray();
    $categorySet = '';
    $categorySet .= "<option value >" . "None" . "</option>";
    foreach($categoryList as $category) {
        $category_id = $category['value'];
        $category_title = $category['label'];
        if($category_id == $categoryId) {
            $categorySet .= "<option value='" . $category_id . "' selected='selected'>" . $category_title . "</option>";
            continue;
        }
        $categorySet .= "<option value='" . $category_id  . "'>" . $category_title . "</option>";
        $categorySet .= "</optgroup>";
    }

    $animationList = $this->_animate->toOptionArray();
    $animationSet = '';
    $animationSet .= "<option>" . $animationList[0]['label'] . "</option>";
    array_shift($animationList);
    foreach($animationList as $optionGroup){
        $label = $optionGroup['label'];
        $animationSet .= "<optgroup label='" . $label . "'>";
        $options = $optionGroup['value'];
        if($options != ''){
            foreach ($options as $option) {
                if($option['value'] == $animation){
                    $animationSet .= "<option value='" . $option['value']  . "' selected='selected'>" . $option['value'] . "</option>";
                    continue;
                }
                $animationSet .= "<option value='" . $option['value']  . "'>" . $option['value'] . "</option>";
            }
        }
        $animationSet .= "</optgroup>";
    }

?>
<form class="entry-edit form-inline" action="<?php echo $block->getUrl('catalog/faqquestion/save', ["_secure" => $this->getRequest()->isSecure()]) ?>" method="post" data-role="form-profile-validate" data-mage-init='{"validation":{}}'>
    <div class="lof-mp-page-title page-title">
        <h2><?php echo __('Edit Question') ?></h2>
        <input type="hidden" name="question_id" class="admin__control-text" value="<?php echo $question->getQuestionId(); ?>" />
        <div class="page-actions-buttons">
            <div class="actions-split save primary" title="Save">
                <button class="action-default primary" title="<?php echo __('Save Question') ?>" type="submit">
                    <span><span><?php echo __('Save Question') ?></span></span>
                </button>
            </div>
        </div>
    </div>
    <div class="fieldset-wrapper admin__collapsible-block-wrapper">
        <div class="fieldset-wrapper-title" data-toggle="collapse" data-target="#general_infomation" aria-expanded="true">
            <strong class="admin__collapsible-title">
                <?php echo __("General Information"); ?>
            </strong>
        </div>
        <div id="general_infomation" class="admin__fieldset-wrapper-content admin__collapsible-content collapse in" aria-expanded="true">
            <fieldset class="admin__fieldset">
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Title"); ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="title" class="admin__control-text required-entry _required" value="<?php echo $question->getTitle(); ?>"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Category"); ?>
                    </label>
                    <div class="admin__field-control">
                        <div class="admin__field-control">
                            <select class="admin__control-select" name="category_id">
                                <?php echo $categorySet ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Answer"); ?>
                    </label>
                    <div class="admin__field-control">
                        <textarea rows="7" id="answer" type="text" name="answer" class="admin__control-text"><?php echo $question->getAnswer(); ?></textarea>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Status"); ?>
                    </label>
                    <div class="admin__field-control">
                        <div class="admin__field-control">
                            <select class="admin__control-select" name="status">
                                <option value="0" <?php if($question->getStatus() == 0) echo "selected='selected' "?> >Disable</option>
                                <option value="1" <?php if($question->getStatus() == 1) echo "selected='selected' "?> >Enable</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Position"); ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="position" class="admin__control-text" value="<?php echo $question->getPosition(); ?>"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h2><?php echo __('Product'); ?></h2>
                                <div class="clearfix"></div>
                            </div>
                            <div class="x_content">
                                <table id="datatable" class="table table-striped table-bordered">
                                    <thead>
                                    <tr class="headings">
                                        <th class=""></th>
                                        <th class="column-title"><?php echo __('ID');?> </th>
                                        <th class="column-title"><?php echo __('Name');?> </th>
                                        <th class="column-title"><?php echo __('SKU');?> </th>
                                        <th class="column-title"><?php echo __('Price');?> </th>
                                        <th class="column-title"><?php echo __('Status');?> </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php

                                    foreach ($block->_productList as $item) {
                                        $productId = $item->getEntityID()
                                        ?>
                                        <tr class="even pointer">
                                            <td class=" "><input type="checkbox" name ="productIds[]" value="<?php echo $productId; ?>" <?php if(in_array($productId, $productIds)) echo 'checked'; ?> ></td>
                                            <td class=" "><?php echo $productId; ?></td>
                                            <td class=" "><?php echo $item->getName(); ?></td>
                                            <td class=" "><?php echo $item->getSKU(); ?></i></td>
                                            <td class=" "><?php echo $item->getPrice(); ?></td>
                                            <td class=" "><?php echo $item->getStatus() == 1 ? __('Enabled') : __('Disable'); ?></td>
                                        </tr>
                                    <?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="fieldset-wrapper admin__collapsible-block-wrapper">
        <div class="fieldset-wrapper-title" data-toggle="collapse" data-target="#design">
            <strong class="admin__collapsible-title">
                <?php echo __("Design"); ?>
            </strong>
        </div>
        <div id="design" class="admin__fieldset-wrapper-content admin__collapsible-content">
            <fieldset class="admin__fieldset">
                <legend class="admin__legend">
                    <span>General</span>
                </legend>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Margin Left (px)"); ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="margin_left" class="admin__control-text" value="<?php echo $question->getMarginLeft(); ?>"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Margin Bottom (px)"); ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="margin_bottom" class="admin__control-text" value="<?php echo $question->getMarginBottom(); ?>"/>
                    </div>
                </div>
            </fieldset>
            <fieldset class="admin__fieldset">
                <legend class="admin__legend">
                    <span>Title</span>
                </legend>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Title Font Size (px)"); ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="title_size" class="admin__control-text" value="<?php echo $question->getTitleSize(); ?>"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Text Color"); ?>
                    </label>
                    <div class="admin__field-control control admin__scope-old">
                        <input type="text" name="title_color" class="minicolors input-text admin__control-text" value="<?php echo $question->getTitleColor(); ?>"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Title Background"); ?>
                    </label>
                    <div class="admin__field-control control admin__scope-old">
                        <input type="text" name="title_background" class="minicolors input-text admin__control-text" value="<?php echo $question->getTitleBackground(); ?>"/>
                    </div>
                </div>
            </fieldset>
            <fieldset class="admin__fieldset">
                <legend class="admin__legend">
                    <span>Title Border</span>
                </legend>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Border Width (px)"); ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="border_width" class="admin__control-text" value="<?php echo $question->getBorderWidth(); ?>"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Border Color"); ?>
                    </label>
                    <div class="admin__field-control control admin__scope-old">
                        <input type="text" name="border_color" class="minicolors input-text admin__control-text" value="<?php echo $question->getBorderColor(); ?>"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Border Radius"); ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="border_radius" class="admin__control-text" value="<?php echo $question->getBorderRadius(); ?>"/>
                    </div>
                </div>
            </fieldset>
            <fieldset class="admin__fieldset">
                <legend class="admin__legend">
                    <span>Icon</span>
                </legend>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Icon Class"); ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="icon" class="admin__control-text" value="<?php echo $question->getIcon(); ?>"/>
                    </div>
                </div>
            </fieldset>
            <fieldset class="admin__fieldset">
                <legend class="admin__legend">
                    <span>Content</span>
                </legend>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Body Color"); ?>
                    </label>
                    <div class="admin__field-control control admin__scope-old">
                        <input type="text" name="body_color" class="minicolors input-text admin__control-text" value="<?php echo $question->getBodyColor(); ?>"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Body Background Color"); ?>
                    </label>
                    <div class="admin__field-control control admin__scope-old">
                        <input type="text" name="body_background" class="minicolors input-text admin__control-text" value="<?php echo $question->getBodyBackground(); ?>"/>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
</form>
<script type="text/javascript">
    require([
        'jquery',
        'mage/adminhtml/wysiwyg/tiny_mce/setup'
    ], function (jQuery) {
        jQuery(document).ready(function() {
            var config = '<?php echo $block->getWysiwygConfig() ?>',
                editor;

            jQuery.extend(config, {
                settings: {
                    theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                    'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                    theme_advanced_buttons2: null,
                    theme_advanced_buttons3: null,
                    theme_advanced_buttons4: null,
                    theme_advanced_statusbar_location: null
                },
                files_browser_window_url: false
            });

            editor = new tinyMceWysiwygSetup(
                'answer',
                config
            );

            editor.turnOn();
        });
    });

    require([
        'jquery',
        'Lofmp_Faq/js/jquery.minicolors.min'
    ], function ($) {
        $('input.minicolors').minicolors();
    });
</script>
