<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>

<?php
$helper                 = $this->helper("Lofmp\StoreLocator\Helper\Data");
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$sellerid_ar = $helper->getSelerid();
$params = $this->getRequest()->getParams();
$product_ar = array();
 
# code..
foreach ($sellerid_ar as $sellerid) {
    # code...

    if(array_key_exists('city', $params)){
    $Seller_city  = $helper->getSellerCity($sellerid);
    
    $city = urldecode($params['city']);
    $country = urldecode($params['country']);
    foreach ($Seller_city as $City) {
        if($city == $City['city'] && $country == $City['country']){
            $product = $helper->getProductIDbySellerid($sellerid);
            $product_ar = array_merge($product_ar, $product);
        }
    }
    }
    elseif (array_key_exists('location', $params)) {
        # code...
    $addressFrom = urldecode($params['location']);
    
    $address  = $helper->getSellerAddress($sellerid);
    
    foreach ($address as $seller_address) {
        
        $distance = $helper->getDistance($addressFrom, $seller_address, "Mi");
        
                if($distance!='F'&&$distance<=$params['radius']){
                $product = $helper->getProductIDbySellerid($sellerid);
            // echo 'SI'+$sellerid;
            // echo $seller_address;
                $product_ar = array_merge($product_ar, $product);
        }
    }
    }
}
   

$_categoryFactory = $objectManager->get('Magento\Catalog\Model\CategoryFactory');
$categoryTitle = urldecode($params['category']);

$collection = $_categoryFactory->create()->getCollection()->addAttributeToFilter('name',$categoryTitle)->setPageSize(1);
if ($collection->getSize()) {
    $categoryId = $collection->getFirstItem()->getId();      
}
$key='';
if(array_key_exists('keyword', $params)){
    $key = urldecode($params['keyword']);
}
$blockObj= $block->getLayout()->createBlock('Lofmp\StoreLocator\Block\StoreLocator\Index');
//print_r($product_ar);
$_productCollection = $objectManager->create('Magento\Catalog\Model\Category')->load( $categoryId )
             ->getProductCollection()
             ->addAttributeToSelect('*')
             ->addAttributeToFilter('status', 1)
             ->addAttributeToFilter('entity_id', array('in' => $product_ar))
             ->addAttributeToFilter('name', array('like' => "%$key%"))
             ;
   

if(array_key_exists('product_list_order', $params)){
    $sort = urldecode($params['product_list_order']);
}
else{
    $sort = 'position';
}

    if(array_key_exists('product_list_dir', $params)){
        $dir = 'DESC';
    }
    else{
        $dir = 'ASC';
    }
    $_productCollection->setOrder($sort, $dir);
    if(array_key_exists('product_list_limit', $params)){
    $limit = urldecode($params['product_list_limit']);
    }
else{
    $limit = 9;
}

if(array_key_exists('p', $params)){
    $p = urldecode($params['p']);
}
else{
    $p = 1;
}
$_productCollection->setPageSize($limit)
    ->setCurPage($p);
?>
<?php
$api_key                = $helper->getConfig('general/api_key');
$pagination             = $helper->getConfig('general/pagination');
$store_limit            = $helper->getConfig('general/store_limit');
$store_perpage          = $helper->getConfig('general/store_perpage');
$enable_category_filter = $helper->getConfig('general/enable_category_filter');
$enable_tag_filter      = $helper->getConfig('general/enable_tag_filter');
$default_radius         = $helper->getConfig('general/default_radius');
$default_radius         = $default_radius?(int)$default_radius:40;
$location_lng           = $helper->getConfig('location/location_lng');
$location_lat           = $helper->getConfig('location/location_lat');
$zoom                   = (int) $helper->getConfig('location/zoom');
$pub                    = $block->getViewFileUrl('Lofmp_StoreLocator/js/plugins/storelocator/templates');
$infoTemplate           = $pub . '/infowindow-description.html';
$locationTemplate       = $pub . '/location-list-description.html';
$dataLocation           = $blockObj->getMediaUrl() . 'storelocator/index/locations';
$tagcollection          = $blockObj->getTagCollection();
$categoryCollection     = $blockObj->getCategoryCollection();
$zipcodeCollection      = $blockObj->getListZipCode();
$countryCollection      = $blockObj->getListCountry();
$cityCollection         = $blockObj->getListCity();
$dataCountry            = $blockObj->getCountry();
$Url                   = $this->getBaseUrl();
$unit          = "km"; //m or km
$unit_label       = "Mi"; //Mi or Km
if($unit == "km") {
  $unit_label = "Km";
}
?>

<div class="storelocator bh-sl-container">
    <div class="bh-sl-form-container">
        <form id="bh-sl-user-location" method="post" action="#">
            <ul id="myTabs" class="nav nav-pills" role="tablist">
                <li role="presentation" class="active"><a href="#search-distance" aria-controls="search-distance" role="tab" data-toggle="tab"> <i class="fa fa-anchor"></i> <?php echo __('Search by Distance'); ?></a></li>
                <li role="presentation"><a href="#search-all" aria-controls="search-all" role="tab" data-toggle="tab"> <i class="fa fa-rocket"></i> <?php echo __('Search by Area'); ?></a></li>
            </ul>
            <div class="bh-sl-tab-panel-content tab-content col-xs-12">
                <div role="tabpanel" class="tab-pane active" id="search-distance">
                    <div class="form-group col-md-4 col-sm-4 col-xs-12">
                        <input class="form-control" type="text" id="bh-sl-address" name="bh-sl-address" placeholder="<?php echo __('Address'); ?>" />
                    </div>
                    <div class="form-group col-md-4 col-sm-4 col-xs-12 slider-range-min">
                        <div id="bh-sl-max-distance" class="bh-sl-max-distance "></div>
                        <span id="bh-sl-show-unit" class="slider-range-amount"></span>
                        <input id="bh-sl-input-distance" type="hidden" name="input-distance" value=""/>
                    </div>
                  

                </div>
                <div role="tabpanel" class="tab-pane" id="search-all">
                    <div class="bh-sl-filters-container">
                      
                        <div class="form-group col-sm-4 col-xs-12 padding-right padding-left">
                            <div id="city-filter" class="bh-sl-filters">
                                <select name="city" class="form-control select">
                                    <option value=""><?php echo __('-- Select City --'); ?></option>
                                    <?php foreach ($cityCollection as $item): ?>
                                        <option value="<?php echo $item; ?>"><?php echo $item; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                       
                        <div class="form-group col-sm-4 col-xs-12 padding-right padding-left">
                            <div id="country-filter" class="bh-sl-filters">
                                <select name="country" class="form-control select">
                                    <option value=""><?php echo __('-- Select Country --'); ?></option>
                                    <?php foreach ($dataCountry as $item): ?>
                                        <option value="<?php echo $item; ?>"><?php echo $item; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        
                        
                    </div>
                </div>
                <!-- filter category -->
                <div class="bh-sl-filters-container">
                  <div class="form-group col-sm-3 col-xs-12 pull-right button-box text-right">
                            <button id="button1" class="bh-sl-submit primary" class="bh-sl-submit" type="button" " ><?php echo __('Search'); ?></button>
                            <button class="bh-sl-reset primary" type="button"><?php echo __('Reset'); ?></button>
                        </div>
                      <div id="ecsearch_form" class="form-group form-group col-md-4 col-sm-4 col-xs-12 padding-right padding-left">
                            <input id="bh-sl-search" name="bh-sl-search" placeholder="<?php echo __('Product Name'); ?>" class="input-search-store-name form-control" type="text">
                        </div>
               </div>
    </div>

</form>
</div>

<?php

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php

    
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty" style="position: static !important;  "><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php $toolbar = $block->getToolbarBlock();
    //$toolbar->setCollection($this->getChild('catalog_product_list')->getLoadedProductCollection());
    
    

        // set collection to toolbar and apply sort
        $toolbar->setCollection($_productCollection);
    echo $toolbar->toHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>


    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                       class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<?php echo $api_key; ?>&sensor=false&libraries=places"></script>
<script type="text/javascript">

        var current_location_lat = 0;
        var current_location_long = 0;
        var current_lat_long = "";
        function getStoreCurrentLocation() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(showCurrentPosition);
            } else {
                console.log("\n<?php echo __('Geolocation is not supported by this browser.');?>");
            }
        }
        function showCurrentPosition(position) {
            current_location_lat = position.coords.latitude;
            current_location_long = position.coords.longitude;
            current_lat_long = {lat: parseFloat(current_location_lat), lng: parseFloat(current_location_long)};

            geocodeGetCurrentAddress("#bh-sl-address");
        }

        function geocodeGetCurrentAddress(input_selector) {
            require(['jquery'],function ($) {
                var geocoder = new google.maps.Geocoder;
                if(geocoder && current_lat_long && ($(input_selector).length > 0)) {
                    geocoder.geocode({'location': current_lat_long}, function(results, status) {
                        if (status === 'OK') {
                            if (results[0]) {
                               var current_address = results[0].formatted_address;
                               $(input_selector).val(current_address);
                            } else {
                              console.log('\n<?php echo __('No results found');?>');
                            }
                          } else {
                            console.log('\n<?php echo __('Geocoder failed due to: ');?>' + status);
                          }
                        });
                }
            });
        }

require(['jquery', 'handlebars', 'markerwithlabel',  'storelocator', 'bootstrap', 'jquery/ui'],function ($) {
        $(document).ready(function ($) {
            $("#bh-sl-max-distance").slider({
                range: "min",
                value: <?php echo $default_radius; ?>,
                min: 1,
                max: 3000,
                slide: function( event, ui ) {
                    $( "#bh-sl-show-unit" ).text( ui.value + " <?php echo $unit_label; ?>" );
                    $( "#bh-sl-input-distance" ).val( ui.value );
                }
            });
            $( "#bh-sl-show-unit" ).text( $( "#bh-sl-max-distance" ).slider( "value" ) + " <?php echo $unit_label; ?>" );
            $( "#bh-sl-input-distance" ).val( $( "#bh-sl-max-distance" ).slider( "value" ) );
            $('#myTabs a:first').tab('show');
            var input = document.getElementById('bh-sl-address');
            var autocomplete = new google.maps.places.Autocomplete(input);
            <?php if(isset($distance) && $distance=='F'){?>
            alert('<?php echo __("your address not right,Please search again!");?>');
              <?php
                }
                ?>
              $("#button1").click(function() {
               
                    url = '<?php echo $Url ?>storelocator/search/index?';
                    var unit = 'km';
                    var type_search = 'location';
                    var radius = $( "#bh-sl-input-distance" ).val();
                    var glocation = '';
                    var city ='';
                    var country ='';
                    var category ='<?php echo $categoryTitle?>';
                    var keyword = $("#bh-sl-search").val();
                    glocation = $("#bh-sl-address").val();
                    city      = $("#city-filter option:selected").text();
                    country      = $("#country-filter option:selected").text();
                     if(glocation==""&& city =="-- Select City --" && country =="-- Select Country --"){
                       var r = confirm("<?php echo __('Please enter location') ?>");
                      if (r == true) {
                          document.getElementById("bh-sl-address").focus();
                      } 
                     }
                     if(glocation==""&& city !="-- Select City --" && country =="-- Select Country --"){
                       var r = confirm("<?php echo __('Please enter country') ?>");     
                     }
                      if(glocation==""&& city =="-- Select City --" && country !="-- Select Country --"){
                       var r = confirm("<?php echo __('Please enter city') ?>");
                     }
                    if(glocation != ""){
                        $.cookie('eclocation', glocation, { expires: 1, path: '/'  });
                        url += 'category='+category+'&unit='+unit+'&type_search=address'+'&radius='+radius+'&submit_ecproductsnearby=Submit';

                        url += '&location=' + encodeURI(glocation);
                         if(keyword!="")
                            url += '&keyword='+encodeURI(keyword);
                        var res = encodeURI(url);
                        window.location = res;
                    }
                    if(glocation==""&& city !="-- Select City --" && country !="-- Select Country --"){
                        url +='category='+category+'&city='+encodeURI(city)+'&country='+encodeURI(country);
                        if(keyword!="")
                            url += '&keyword='+encodeURI(keyword);
                        var res = encodeURI(url);
                        window.location = res;
                        window.location =url;
                    }
                });

              if(typeof(google) != "undefined") {
                getStoreCurrentLocation();
              }
        });
        
        
            
    });
</script>

</div>

