<?php
/** @var \Lofmp\GdprSeller\Block\Seller\DeleteProfile $block */

$deleteSellerUrl = $block->getDeleteSellerUrl();
$deleteSellerProfileUrl = $block->getDeleteProfileUrl();
?>
<script>
    require([
        'jquery',
        'mage/translate',
        'Magento_Ui/js/modal/confirm'
    ], function ($, $t, confirm){
        $('.page-actions-buttons').prepend('<button type="button" class="action-default secondary" id="delete_seller" role="delete-seller"><?= /** @noEscape */ __('Delete seller') ?></button>');

        $(document).on('click', '#delete_seller', function() {
            confirm({
                title: $.mage.__('<?= /** @noEscape */ __('Delete Seller') ?>'),
                content: $.mage.__('<?= /** @noEscape */ __('Are you sure you want to delete seller account?') ?>'),
                actions: {
                    /** Confirm (OK) */
                    confirm: function(){
                        window.location.href = '<?= $deleteSellerUrl?>';
                    },
                    /** Cancel */
                    cancel: function(){ /* no-op */ }
                }
            });
        });
    });
</script>
<style>
    .page-actions-buttons button {
        margin-right: 5px !important;
    }
</style>
