<?php
$jsonHelper = $this->helper('Magento\Framework\Json\Helper\Data');
?>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert'
    ], function ($, alert) {
        window.LofSmtpEmailDebugTest = function(){
            
            $.ajax({
                url: '<?php echo $block->getAdminUrl() ?>',
                type: 'post',
                dataType: 'html',
                data: {
                    form_key: FORM_KEY,
                    auth: $('#lofsmtpemail_smtp_config_auth').val(),
                    ssl:$('#lofsmtpemail_smtp_config_ssl').val(),
                    smtphost:$('#lofsmtpemail_smtp_config_smtphost').val(),
                    username:$('#lofsmtpemail_smtp_config_username').val(),
                    password:$('#lofsmtpemail_smtp_config_password').val(),
                    port:$('#lofsmtpemail_smtp_config_port').val(),
                    email:$('#lofsmtpemail_smtp_config_debug_email').val()

                },
                showLoader: true
            }).done(function(data) {
                alert({
                    title:'Result',
                    content:data
                });
            });
        }
    });
</script>

<?php echo $block->getButtonHtml() ?>