<?php
$list_email = $block->getSumEmaillog()->getData();
$count = count($block->getSumEmaillog());
$status = $block->getStatus();
$results = [];
foreach ($status as $k => $v) {
	foreach ($list_email as $_email) {
		if($_email['status'] === $k){
			$results[$k]['status'][] = $_email;
			$results[$k]['y'] = count($results[$k]['status'])/$count;
			$results[$k]['name']  = $v." (".count($results[$k]['status']).")";
		}
	}
}
$items = array();
foreach ($results as $key => $value) :
	unset($value['status']);
	array_push($items,$value);
endforeach;

$data = json_encode($items);
?>
<div id="container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
<?php if(count($items) > 0) : ?>
<script>
	require([
		'jquery',
		'Lof_SmtpEmail/js/highcharts'
		], function($){
			$('#container').highcharts({
				chart: {
					plotBackgroundColor: null,
					plotBorderWidth: null,
					plotShadow: false,
					type: 'pie'
				},
				title: {
					text: '<?= $block->escapeHtml(__('Email Logs Report Chart (Totals: %1)', $count)) ?>'
				},
				tooltip: {
					pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
				},
				plotOptions: {
					pie: {
						allowPointSelect: true,
						cursor: 'pointer',
						dataLabels: {
							enabled: true,
							format: '<b>{point.name}</b>: {point.percentage:.1f} %',
							style: {
								color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
							}
						}
					}
				},
				series: [{
					name: 'Total',
					colorByPoint: true,
					data: <?= $data;?>
				}]
			});
		});
</script>
<?php endif; ?>
