<?php
/**
 * negotiate-tabs
 *
 * @copyright Copyright © 2020 landofcoder. All rights reserved.
 * @author    landofcoder@gmail.com
 */
?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__($block->getProduct()->getSellerId() ? 'Seller and Customer' :'Contact And Message')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <?php if (!$block->getProduct()->getSellerId()): ?>
            <div class="admin__page-section-item manage-request-message-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Message')) ?></span>
            </div>
            <?= $block->getChildHtml('manage.request.message') ?>
        </div>
        <?php endif; ?>
        <?php if ($block->getProduct()->getSellerId()): ?>
            <div class="admin__page-section-item seller-info">
                <div class="admin__page-section-item-title">
                    <span class="title"><?= $block->escapeHtml(__('Seller Info')) ?></span>
                </div>
                <?= $block->getChildHtml('manage.quote.seller') ?>
            </div>
        <?php endif; ?>
        <div class="admin__page-section-item customer-info">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Customer Info')) ?></span>
            </div>
            <?= $block->getChildHtml('negotiable.quote.customerinfo') ?>
        </div>
    </div>

</section>


