<?php
/**
 * @var $block Lofmp\ChatSystem\Block\Chat\Chat
 */
use Lof\MarketPlace\Model\Seller;

$helper = $this->helper("Lofmp\ChatSystem\Helper\Data");
$market_helper = $this->helper("Lof\MarketPlace\Helper\Seller");
$store = $helper->getConfig('chat/store');
$store = @explode(",", $store);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$chat = $objectManager->create('Lofmp\ChatSystem\Model\Chat');
$is_read = 0;
$currentSellerId = $block->getLoggedinSellerId();
$seller = null;
$isProduct = false;
if ($block->getProduct()) {
    $isProduct = true;
    $product_id = $this->getProduct()->getEntityId();
    $seller_id = $market_helper->getSellerIdByProduct($product_id);
    if ($seller_id != $currentSellerId) {
        $seller = $objectManager->create('Lof\MarketPlace\Model\Seller')->load($seller_id, 'seller_id');
    }
} else {
    $seller = $block->getCurrentSeller();
    $seller_id = $seller && $seller->getId() ? $seller->getId() : 0;
    if ($seller_id == $currentSellerId) {
        $seller = null;
    }
}

$status = $seller && $seller->getId() ? (int)$seller->getStatus() : 0;

if ($this->isLogin()) {
    $chat_message = $chat->load($this->getCustomer()->getValue('customer_email'), 'customer_email');

    $is_read = $chat_message->getData('is_read');
}

if (in_array($helper->getStoreId(), $store) && $store && $helper->getConfig('general_settings/enable') && $seller && $status == Seller::STATUS_ENABLED) :
?>

<div id="live-chat">
    <header class="clearfix" <?php if ($helper->getConfig('chat/background_color')) {
        echo 'style="background-color:'.$block->escapeHtmlAttr($helper->getConfig('chat/background_color')).'"';
    } ?>>
        <a href="#" class="chat-close">x</a>
        <h4><?php
        if (isset($seller)) {
            echo $block->escapeHtml(__('Chat with seller').' '.$seller->getData('name'));
        } else {
            echo $block->escapeHtml($helper->getConfig('chat/text_label'));
        } ?></h4>

        <?php if ($is_read == 3) : ?>
        <span class="chat-message-counter" style="display: inline;">1</span>
        <?php endif; ?>
    </header>
    <div class="chat">
        <?php if (!$this->isLogin()) : ?>
        <ul class="tabs">
            <li class="tab-link current" data-tab="tab-1"><?= __('Guest Chat'); ?></li>
            <li class="tab-link" data-tab="tab-2"><?= __('Login Chat'); ?></li>
        </ul>
        <div id="tab-1" class="tab-content current">
             <div class="form-chat">
                <div class="main-chat" id="main-chat">
                </div>
                <div class="box-chat">
                    <form method="post" id="formSendMsg" onsubmit="return false;">
                        <input type="hidden" name="form_key" value="<?= $block->escapeHtmlAttr($this->getFormKey()); ?>">
                        <input type="hidden" name="seller_id" value="<?= $block->escapeHtmlAttr((int)$seller->getData('seller_id'));?>">
                        <input type="hidden" name="seller_key" value="<?= $block->escapeHtmlAttr($seller->getUrl());?>">
                        <input type="hidden" name="current_url" value="<?= $block->escapeHtmlAttr($this->getCurrentUrl());?>">
                        <input type="text" name="body_msg" placeholder="<?= $block->escapeHtmlAttr(__('Please enter a message')); ?> ...">
                    </form>
                </div>
            </div>
        </div>
        <div id="tab-2" class="tab-content">
            <div class="form-login-chat">
                <form class="form form-login"
                action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
                method="post" id="login-form" data-mage-init='{"validation":{}}'>
                <?= $block->getBlockHtml('formkey'); ?>
                    <fieldset class="fieldset login"
                        data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                        <div class="field note"><?php /* @escapeNotVerified */ echo __('If you have an account, sign in with your email address.') ?></div>
                        <div class="field email required">
                            <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                            <div class="control">
                                <input name="login[username]"
                                    value="<?= $block->escapeHtml($block->getUsername()) ?>"
                                    <?php if ($block->isAutocompleteDisabled()) :?>
                                    autocomplete="off" <?php endif; ?> id="email" type="email"
                                    class="input-text"
                                    title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                                    data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field password required">
                            <label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                            <div class="control">
                                <input name="login[password]" type="password"
                                    <?php if ($block->isAutocompleteDisabled()) :?>
                                    autocomplete="off" <?php endif; ?> class="input-text" id="pass"
                                    title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                                    data-validate="{required:true, 'validate-password':true}">
                            </div>
                        </div>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" class="action login primary" name="send"
                                    id="send2">
                                    <span><?php /* @escapeNotVerified */ echo __('Login') ?></span>
                                </button>
                            </div>
                            <div class="secondary">
                                <a class="action remind"
                                    href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a>
                            </div>
                            <div class="secondary">
                                <a class="action remind"
                                    href="<?php /* @escapeNotVerified */ echo $block->getRegisterUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></a>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
        <?php else : ?>
        <div class="form-chat">
            <div class="main-chat" id="main-chat">

            </div>
            <div class="box-chat">
                <form method="post" id="formSendMsg" onsubmit="return false;">
                    <input type="hidden" name="form_key" value="<?= $block->escapeHtmlAttr($this->getFormKey()); ?>">
                    <input type="hidden" name="seller_id" value="<?= $block->escapeHtmlAttr((int)$seller->getData('seller_id'));?>">
                    <input type="hidden" name="seller_key" value="<?= $block->escapeHtmlAttr($seller->getUrl());?>">
                    <input type="hidden" name="current_url" value="<?= $block->escapeHtmlAttr($this->getCurrentUrl());?>">
                    <input type="text" name="body_msg" placeholder="<?= $block->escapeHtmlAttr(__('Please enter a message')); ?> ...">
                </form>
            </div>
        </div>
        <?php endif; ?>
    </div> <!-- end chat -->
</div> <!-- end live-chat -->
<script type="text/javascript">
    require(['jquery'],function($) {
        (function() {
            $('.chat ul.tabs li').click(function(){
                var tab_id = $(this).attr('data-tab');

                $('.chat ul.tabs li').removeClass('current');
                $('.chat .tab-content').removeClass('current');

                $(this).addClass('current');
                $("#"+tab_id).addClass('current');
            })

            $('#live-chat header').on('click', function() {

                $('.chat').slideToggle(300, 'swing');
                //$('.chat-message-counter').fadeToggle(300, 'swing');

            });

            $('.chat-close').on('click', function(e) {

                e.preventDefault();
                $('#live-chat').fadeOut(300);

            });

        }) ();
        <?php //if($this->isLogin()) {?>
        function removeTags(str) {
            if ((str===null) || (str===''))
                return false;
            else
                str = str.toString();

            // Regular expression to identify HTML tags in
            // the input string. Replacing the identified
            // HTML tag with a null string.
            return str.replace( /(<([^>]+)>)/ig, '');
        }
        function sendMsg() {
            $seller_id = lofescapeHtml($('#formSendMsg input[name="seller_id"]').val());
            $body_msg = lofescapeHtml($('#formSendMsg input[name="body_msg"]').val());
            $current_url = lofescapeHtml($('#formSendMsg input[name="current_url"]').val());
            if($.trim($body_msg)) {
                $body_msg = removeTags($body_msg);
                $('#formSendMsg input[type="text"]').val('');
                $('.main-chat').append('<div class="msg-user"><p>'+$body_msg+'</p><div class="info-msg-user">You</div></div>');

                $.ajax({
                    url : '<?= $this->getUrl('lofmpchatsystem/chat/sendmsg'); ?>',
                    type : 'post',
                    dataType: 'json',
                    data : {
                        seller_id : $seller_id,
                        body_msg : $body_msg,
                        current_url : $current_url
                    }, success : function(data) {
                        console.log(data.seller_id);
                        console.log(data.customer_id);
                        $('#formSendMsg input[type="text"]').val('');
                        var div = document.getElementById('main-chat');
                        if (div) {
                            div.scrollTop = div.scrollHeight - div.clientHeight;
                        }
                    }
                });
            }
        }

        function lofescapeHtml(unsafe) {
            return unsafe
                .replace(/&/g, "&amp;")
                .replace(/</g, "&lt;")
                .replace(/>/g, "&gt;")
                .replace(/"/g, "&quot;")
                .replace(/'/g, "&#039;");
        }

        $('#formSendMsg input[type="text"]').keypress(function() {
            var keycode = (event.keyCode ? event.keyCode : event.which);
            if (keycode == '13') {
                sendMsg();
                var div = document.getElementById('main-chat');
                if (div) {
                    div.scrollTop = div.scrollHeight - div.clientHeight;
                }
                $('.chat-message-counter').css('display','none');
            }
        });

        $('#formSendMsg input[type="text"]').click(function(e) {
            var div = document.getElementById('main-chat');
            if (div) {
                div.scrollTop = div.scrollHeight - div.clientHeight;
            }
        });

        $('.main-chat').load('<?= $this->getUrl('lofmpchatsystem/chat/msglog', ["seller_id" => (int)$seller->getData('seller_id')]); ?>');
        $.ajaxSetup({cache:false});
        setInterval(function() {
            $('.main-chat').load('<?= $this->getUrl('lofmpchatsystem/chat/msglog', ["seller_id" => (int)$seller->getData('seller_id')]); ?>');
             var div = document.getElementById('main-chat')
            div.scrollTop = div.scrollHeight - div.clientHeight;
        }, 5000);
    });
</script>

<?php
endif;
?>
