<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_invoice = $block->getInvoice() ?>
<?php $_order   = $block->getOrder() ?>
<?php
if (!empty($_order)):
    if (!empty($_order->getData('delivery_date'))):
        ?>
        <h3 class="title"><?= $block->escapeHtml(__('Delivery Time Slot')) ?></h3>
        <span class="title"><b><?= $block->escapeHtml(__('Date: ')) ?><b></span>
        <?php echo $block->escapeHtml(date("d-m-Y", strtotime($_order->getData('delivery_date')))); ?>
        <span class="title"><b><?= $block->escapeHtml(__(' Time: ')) ?><b></span>
        <?php echo $block->escapeHtml($_order->getData('delivery_time_slot')); ?><br>
    <?php
    endif;
endif; ?>

<?php if ($_invoice && $_order): ?>
    <table class="email-items">
        <thead>
        <tr>
            <th class="item-info">
                <?= /* @escapeNotVerified */  __('Items') ?>
            </th>
            <th class="item-qty">
                <?= /* @escapeNotVerified */  __('Qty') ?>
            </th>
            <th class="item-subtotal">
                <?= /* @escapeNotVerified */  __('Subtotal') ?>
            </th>
        </tr>
        </thead>
        <?php foreach ($_invoice->getAllItems() as $_item): ?>
            <?php
            if ($_item->getOrderItem()->getParentItem()):
                continue;
            endif;
            ?>
            <tbody>
            <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot class="order-totals">
        <?= $block->getChildHtml('invoice_totals') ?>
        </tfoot>
    </table>
<?php endif; ?>
