<?php

$categoryCollection = $this->_categoryFactory->getParentTitle();

?>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2><?php echo __('Manager Category'); ?></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                    <tr class="headings">
                        <th class="column-title"><?php echo __('Title');?> </th>
                        <th class="column-title"><?php echo __('Parent Category');?> </th>
                        <th class="column-title no-sort"><?php echo __('Description');?> </th>
                        <th class="column-title"><?php echo __('Status');?> </th>
                        <th class="column-title"><?php echo __('Position');?> </th>
                        <th class="column-title"><?php echo __('Created');?> </th>
                        <th class="column-title"><?php echo __('Modified');?> </th>
                        <th class="column-title no-sort"></th>
                        <th class="column-title no-sort"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php

                    foreach ($categoryCollection as $category) {

                        ?>
                        <tr class="even pointer">
                            <td class=" "><?php echo $category->getTitle(); ?></td>
                            <td class=" "><?php echo $category->getData('parent_title'); ?></i></td>
                            <td class=" "><?php echo $category->getDescription(); ?></td>
                            <td class=" "><?php echo $category->getStatus() == 1 ? __('Enabled') : __('Disable'); ?></td>
                            <td class=" "><?php echo $category->getPosition(); ?></td>
                            <td class=" "><?php echo $category->getCreationTime(); ?></td>
                            <td class=" "><?php echo $category->getUpdateTime(); ?></td>
                            <td class=" "><a href="<?php echo $block->getUrl('catalog/faqcategory/edit/id/' . $category->getCategoryId(), ['_secure' => $this->getRequest()->isSecure()]); ?>"><?php echo 'Edit'; ?></a></td>
                            <td class=" "><a href="<?php echo $block->getUrl('catalog/faqcategory/delete/id/' . $category->getCategoryId(), ['_secure' => $this->getRequest()->isSecure()]); ?>"><?php echo 'Delete'; ?></a></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    require(['jquery', 'jquery/dataTables'], function($){
        jQuery(document).ready(function($) {
            $('#datatable').DataTable( {
                "columnDefs": [ {
                    "targets": 'no-sort',
                    "orderable": false,
                } ]
            } );
        });
    });
</script>