<?php
    $categoryCollection = $this->_categoryFactory;
    $categoryList = $categoryCollection->toOptionArray();
    $categorySet = '';
    $categorySet .= "<option value selected='selected'>" . "None" . "</option>";
    foreach($categoryList as $category) {
        $category_id = $category['value'];
        $category_title = $category['label'];
        $categorySet .= "<option value='" . $category_id  . "'>" . $category_title . "</option>";
        $categorySet .= "</optgroup>";
    }

    $animationList = $this->_animate->toOptionArray();
    $animationSet = '';
    $animationSet .= "<option value selected='selected'>" . $animationList[0]['label'] . "</option>";
    array_shift($animationList);
    foreach($animationList as $optionGroup){
        $label = $optionGroup['label'];
        $animationSet .= "<optgroup label='" . $label . "'>";
        $options = $optionGroup['value'];
        if($options != ''){
            foreach ($options as $option) {
                $animationSet .= "<option value='" . $option['value']  . "'>" . $option['value'] . "</option>";
            }
        }
        $animationSet .= "</optgroup>";
    }

?>
<form class="entry-edit form-inline" action="<?php echo $block->getUrl('catalog/faqcategory/save', ["_secure" => $this->getRequest()->isSecure()]) ?>" method="post" data-role="form-profile-validate" data-mage-init='{"validation":{}}'>
    <input type="hidden" name="store_id" class="admin__control-text" value="<?php //echo $helper->getCurrentStoreId(); ?>" />
    <div class="lof-mp-page-title page-title">
        <h2><?php echo __('New Category') ?></h2>
        <div class="page-actions-buttons">
            <div class="actions-split save primary" title="Save">
                <button class="action-default primary" title="<?php echo __('Save Category') ?>" type="submit">
                    <span><span><?php echo __('Save Category') ?></span></span>
                </button>
            </div>
        </div>
    </div>
    <div class="fieldset-wrapper admin__collapsible-block-wrapper">
        <div class="fieldset-wrapper-title" data-toggle="collapse" data-target="#general_infomation" aria-expanded="true">
            <strong class="admin__collapsible-title">
                <?php echo __("General Information"); ?>
            </strong>
        </div>
        <div id="general_infomation" class="admin__fieldset-wrapper-content admin__collapsible-content collapse in" aria-expanded="true">
            <fieldset class="admin__fieldset">
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Title"); ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="title" class="admin__control-text required-entry _required"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Parent Category"); ?>
                    </label>
                    <div class="admin__field-control">
                        <div class="admin__field-control">
                            <select class="admin__control-select" name="parent_id">
                                <?php echo $categorySet ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Description"); ?>
                    </label>
                    <div class="admin__field-control">
                        <textarea rows="7" id="description" type="text" name="description" class="admin__control-text" value="" ></textarea>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Status"); ?>
                    </label>
                    <div class="admin__field-control">
                        <div class="admin__field-control">
                            <select class="admin__control-select" name="status">
                                <option value="0" selected="selected">Disable</option>
                                <option value="1">Enable</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Position"); ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="position" class="admin__control-text" value="" />
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="fieldset-wrapper admin__collapsible-block-wrapper">
        <div class="fieldset-wrapper-title" data-toggle="collapse" data-target="#design">
            <strong class="admin__collapsible-title">
                <?php echo __("Design"); ?>
            </strong>
        </div>
        <div id="design" class="admin__fieldset-wrapper-content admin__collapsible-content">
            <fieldset class="admin__fieldset">
                <legend class="admin__legend">
                    <span>General</span>
                </legend>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Margin Left (px)"); ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="margin_left" class="admin__control-text"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Margin Bottom (px)"); ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="margin_bottom" class="admin__control-text"/>
                    </div>
                </div>
            </fieldset>
            <fieldset class="admin__fieldset">
                <legend class="admin__legend">
                    <span>Title</span>
                </legend>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Title Font Size (px)"); ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="title_size" class="admin__control-text"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Text Color"); ?>
                    </label>
                    <div class="admin__field-control control admin__scope-old">
                        <input type="text" name="title_color" class="minicolors input-text admin__control-text"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Title Background"); ?>
                    </label>
                    <div class="admin__field-control control admin__scope-old">
                        <input type="text" name="title_background" class="minicolors input-text admin__control-text"/>
                    </div>
                </div>
            </fieldset>
            <fieldset class="admin__fieldset">
                <legend class="admin__legend">
                    <span>Title Border</span>
                </legend>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Border Width (px)"); ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="border_width" class="admin__control-text"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Border Color"); ?>
                    </label>
                    <div class="admin__field-control control admin__scope-old">
                        <input type="text" name="border_color" class="minicolors input-text admin__control-text"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Border Radius"); ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="border_radius" class="admin__control-text"/>
                    </div>
                </div>
            </fieldset>
            <fieldset class="admin__fieldset">
                <legend class="admin__legend">
                    <span>Icon</span>
                </legend>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Icon Class"); ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="icon" class="admin__control-text"/>
                    </div>
                </div>
            </fieldset>
            <fieldset class="admin__fieldset">
                <legend class="admin__legend">
                    <span>Content</span>
                </legend>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?php echo __("Body Background Color"); ?>
                    </label>
                    <div class="admin__field-control control admin__scope-old">
                        <input type="text" name="body_background" class="minicolors input-text admin__control-text"/>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
</form>
<script type="text/javascript">
    require([
        'jquery',
        'mage/adminhtml/wysiwyg/tiny_mce/setup'
    ], function (jQuery) {
        jQuery(document).ready(function() {
            jQuery('input[type="checkbox"]').each(function(){
                jQuery(this).bind('change', function () {
                    if(jQuery(this).prop('checked')) {
                        jQuery(this).val(1);
                    } else {
                        jQuery(this).val(0);
                    }
                });
            });
            var config = '<?php echo $block->getWysiwygConfig() ?>',
                editor;

            jQuery.extend(config, {
                settings: {
                    theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                    'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                    theme_advanced_buttons2: null,
                    theme_advanced_buttons3: null,
                    theme_advanced_buttons4: null,
                    theme_advanced_statusbar_location: null
                },
                files_browser_window_url: false
            });

            editor = new tinyMceWysiwygSetup(
                'description',
                config
            );

            editor.turnOn();
        });
    });

    require([
        'jquery',
        'Lofmp_Faq/js/jquery.minicolors.min'
    ], function ($) {
        $('input.minicolors').minicolors();
    });
</script>
